require 'fileutils'
require 'pathname'
require File.dirname(__FILE__) + File::Separator + 'lib/kenny_repo.rb'
require File.dirname(__FILE__) + File::Separator + 'lib/kenny_patch.rb'
require File.dirname(__FILE__) + File::Separator + 'lib/root_patch.rb'
require File.dirname(__FILE__) + File::Separator + 'lib/add_patch.rb'
require File.dirname(__FILE__) + File::Separator + 'lib/modify_patch.rb'
require File.dirname(__FILE__) + File::Separator + 'lib/merge_patch.rb'
